[package]
name = "the_async"
version = "0.1.0"
authors = ["itoktsnhc <itoktsnhc@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3", features = ["compat"] }
hyper = "0.14.16"
