[package]
name = "by_the_book"
version = "0.1.0"
authors = ["itoktsnhc <itoktsnhc@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
