[package]
name = "the_web"
version = "0.1.0"
authors = ["itoktsnhc <itoktsnhc@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
chrono = "0.4"
mysql = "*"
serde_json = "1.0"
